version: "3.7"
services:
  api:
    container_name: api
    build:
      context: .
    tty: true
    depends_on:
      - database
    restart: unless-stopped
    ports:
      - "${APP_PORT}:${APP_PORT}"
      - "${APP_DEBUGGER_PORT}:${APP_DEBUGGER_PORT}"
    volumes:
      - ./:/srv/posterr
    env_file:
      - .env.dev
    environment:
      - NODE_ENV=${NODE_ENV}
      - NODE_PATH=dist/src
      - PORT=${PORT}
      - DB_PORT=3306
      - DB_HOST=database
    command: yarn start:dev

  database:
    # @todo some improvement on mysql authentication method should be added
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - .env.dev
    environment:
      MYSQL_DATABASE: ${APP_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - database
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
      #- ./.docker/sql:/docker-entrypoint-initdb.d
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 20s


networks:

  backend:
    driver: bridge
  database:
    driver: bridge

volumes:
  dbdata:
    driver: local
    labels:
      mf.project.name: ${APP_NAME}